env:
  browser: true
  es6: true
  jest: true
extends: ['eslint:recommended', 'plugin:react/all']
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - jest
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  max-len:
    - error
    - 120
  react/jsx-no-bind: 0
  no-unused-vars: [error, {"argsIgnorePattern": ^_ }]
  react/forbid-prop-types: [error, {forbid: ["any"]}]
  react/jsx-indent: [error, 2]
  react/jsx-filename-extension: [1, {extensions: [".js", ".jsx"]}]
  react/jsx-closing-bracket-location: [error, "after-props"]
  react/forbid-component-props: [error, { forbid: ["style"]}]
  react/prefer-stateless-function: [error, {"ignorePureComponents": true}]
  react/jsx-max-props-per-line: off
  react/jsx-no-literals: off
  react/no-multi-comp: off
  react/no-set-state: off
  no-useless-escape: off
  react/jsx-closing-tag-location: off
  react/default-props-match-prop-types: off
  react/require-default-props: off
  react/no-redundant-should-component-update: off
  react/no-unused-state: off
  react/no-direct-mutation-state: off
  react/no-typos: off
  react/jsx-curly-brace-presence: off
  react/jsx-child-element-spacing: off
  react/jsx-one-expression-per-line: off
  react/no-access-state-in-setstate: off
  react/destructuring-assignment: off
  react/jsx-max-depth: off
  react/jsx-sort-default-props: off
  react/no-deprecated: off
  jest/valid-expect: warn
  jest/consistent-test-it: warn
