version: 2
jobs:
  build:
    working_directory: ~/repo

    docker: # use the docker executor type; machine and macos executors are also supported
     - image: circleci/ruby:2.5.1-node-browsers
       environment:
         RAILS_ENV: test
         PGHOST: 127.0.0.1
         PGUSER: list_app_v2
         SELENIUM_DRIVER_URL: http://localhost:4444/wd/hub

     - image: circleci/postgres:9.5.13
       environment:
         POSTGRES_USER: list_app_v2
         POSTGRES_DB: list_app_v2_test

     - image: selenium/standalone-firefox:latest

    steps:
      - checkout # check out the code in the project directory
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: bundle install

      - run:
          name: install npm
          command: npm install

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # run rubocop
      - run: rubocop

      # run reek
      - run: reek -c defaults.reek.yml

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir -p /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/controllers/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec --format documentation \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml \
                              -- $(echo "${TEST_FILES}" | sed -e 's/\n/\\n/' -e 's/ /\ /')

      - run:
          name: jest
          command: cd client && npm run test

      # run eslint
      - run:
          name: eslint
          command: cd client && npm run eslint

      # deploy to heroku
      - deploy:
          name: deploying
          command: |
            git push -f https://heroku:fb82039c-b09f-403c-86b6-a7c62fa0b803@git.heroku.com/ancient-fjord-53537.git redux:master

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
