default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: list_app_v2_development

test:
  <<: *default
  database: list_app_v2_test

production:
  <<: *default
  database: list_app_v2_production
  username: list_app_v2
  password: <%= ENV['LIST_APP_V2_DATABASE_PASSWORD'] %>
